language: groovy
jdk:
- openjdk8
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install graphviz
- sudo pip install awscli
git:
  submodules: false
env:
  global:
  - GRADLE_OPTS='-Dorg.gradle.daemon=false'
script:
- make test
after_script:
- bash pub-tests.sh travis
